### ISSUE TITLE
doesnt build on OSX 10.7

### ISSUE THREAD

**Issue by max-mapper** [brianb/mdbtools#13]
not a priority as I have a unix box that this builds successfully on, but I figured I should open the issue in case others are googling

first I get

```
write.c:39: error: only weak aliases are supported in this configuration
write.c:49: error: only weak aliases are supported in this configuration
write.c:59: error: only weak aliases are supported in this configuration
```

when I edit the lines to add `weak` e.g. `__attribute__((weak, alias("mdb_put_int32_msb")));` I get this:

```
write.c:33: warning: alias definitions not supported; ignored
write.c:43: warning: alias definitions not supported; ignored
write.c:53: warning: alias definitions not supported; ignored
```

and then further down

```
ld: unknown option: --version-script=./libmdb.map
collect2: ld returned 1 exit status
```
